name = "arunika-monitoring"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
main = "src/main.tsx"
compatibility_date = "2024-01-01"

[build]
command = "npm install && npm run build"
cwd = ""
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[env.production]
name = "arunika-monitoring-prod"
routes = [
  { pattern = "arunika.example.com", zone_name = "example.com" }
]
